Repository lion-packages/test, pull requests merged in 2025-01, with the labels that each got.

#20 Added PHPStan support and validation
  .github/workflows/php.yml
  src/LionTest/Test.php
  tests/Provider/TestProviderTrait.php
Labels: enhancement, continuous integration

#21 GitHub Actions configuration updated
  .github/workflows/php.yml
  .gitignore
  phpunit.xml
Labels: continuous integration

#22 Update LICENSE
  LICENSE
Labels: documentation
