Repository lion-packages/test, pull requests merged in 2025-04, with the labels that each got.

#26 Integrate Dependency-Review
  .github/workflows/php.yml
Labels: continuous integration

#27 Integrate PHPLint
  .github/workflows/php.yml
  .gitignore
  composer.json
Labels: continuous integration

#28 Add Dependabot configuration
  .github/dependabot.yml
Labels: continuous integration

#29 Update README
  .github/README.md
Labels: documentation

#30 The infection library is installed
  composer.json
  infection.json
  src/LionTest/Test.php
  tests/TestTest.php
Labels: dependencies, tests

#31 Infection is integrated
  .github/workflows/php.yml
Labels: continuous integration

#32 Update dependabot.yml
  .github/dependabot.yml
Labels: continuous integration

#35 Apply fixes from StyleCI
  src/LionTest/Test.php
  tests/Provider/TestProviderTrait.php
  tests/TestTest.php
Labels: standardization

#34 Added StyleCI configuration
  .styleci.yml
  tests/Provider/ExceptionProviderClass.php
  tests/Provider/TestProviderTrait.php
  tests/TestTest.php
Labels: continuous integration

#36 Adding a condition to run test coverage in Github Actions (Pull Request)
  .github/workflows/php.yml
Labels: continuous integration

#37 Define the execution time for Github Actions
  .github/workflows/php.yml
Labels: continuous integration
